### PR TITLE
Support boolean attributes / Remove autogenerated files

### PR DESCRIPTION
**Pull request by yoshrc**
I made 2 major changes.

## Support boolean attributes for HTML tags
For example, `script[src defer.]` expands to `<script src="" defer></script>`. This notation is not documented in the [cheet sheet](https://docs.emmet.io/cheat-sheet/), but you can use it in the [playground](https://docs.emmet.io/). We should support boolean attributes for the other filters as well, say, haml.

## Remove autogenerated files
Generally, files generated by build should not exist in the repository. If the files need to exist somehow, please tell me the reason.

### CODE REVIEW

**Comment by yoshrc** [comment]
I find that changes in 16c76d0 are lost by my changes. I temporarily close the PR.

**Comment by yoshrc** [comment]
I restored the lost changes. I confirmed that all lost changes were restored by the following way:

1. checkout `master`
2. `make clean && make`
3. `git diff `

All lost changes were displayed as a diff of `emmet-mode.el`. I applied these changes to the appropriate files in `src`.

**Comment by smihica** [comment]
> ## Remove autogenerated files
> Generally, files generated by build should not exist in the repository. If the files need to exist somehow, please tell me the reason.

Because melpa will use emmet-mode.el

**Comment by smihica** [comment]
I've merged first part of this on https://github.com/smihica/emmet-mode/commit/bfe0014ec2f760f303608c3bf41eb42887a982f9
Thank you.

**Pull request closed without merging**
